name: Build and Test

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build_plugin:
    name: Build and Test
    runs-on: ${{ matrix.os.runner }}

    strategy:
      matrix:
        os:
        - runner: macos-latest
        - runner: windows-latest
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -B build

    - name: Build
      working-directory: build
      run: cmake --build . --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: build
      run: ctest
